version: '3'

services:

  web:
    container_name: react-docker
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3030:3030'
    networks:
     - app-network

  cypress:
    image: "cypress/included:10.8.0"
    container_name: cypress
    restart: unless-stopped
    volumes: 
      - ./cypress:/cypress
      # - ./e2e/cypress:/cypress/cypress
      - ./cypress.config.js:/cypress.config.js
    networks:
     - app-network
    # hostname: "localhost"
    # domainname: http://localhost:3030/
    hostname: http://localhost:3030/
    # environment:
    #   - CYPRESS_baseUrl=http://localhost:3030/

networks:
    app-network:
        driver: bridge
  