version: '3'

services:

  web:
    container_name: react-docker
    restart: unless-stopped
    image: testreact
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '3080:3080'
    networks:
     - app-network

  cypress:
    image: "cypress/included:10.8.0"
    container_name: cypress-react
    volumes: 
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js
    environment:
      - CYPRESS_baseUrl=http://web:3080
    command: npx cypress run
    networks:
     - app-network
    depends_on:
      - web

networks:
    app-network:
        driver: bridge