version: '3'

services:
  e2e-chrome:
    image: "cypress/included:10.8.0"
    container_name: cypress
    # "cypress/included" images have entrypoint set to globally installed cypress
    # so the command can simply add any arguments
    command: "--browser electron"
    volumes:
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js
